# Generated by Django 3.2.1 on 2021-07-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='cookie',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='group',
            name='webvpn',
            field=models.CharField(default='', max_length=100),
        ),
    ]
