# Generated by Django 3.2.1 on 2021-07-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VulnScanModel', '0008_vulnscan_specify'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnscan',
            name='cookies',
            field=models.CharField(default='', max_length=500),
        ),
    ]
