# Generated by Django 3.2.1 on 2021-07-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0002_rename_vulnscan_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='username',
        ),
    ]
