# Generated by Django 3.2.1 on 2021-07-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceScanModel', '0006_servicescan_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicescan',
            name='cookies',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='servicescan',
            name='webvpn',
            field=models.CharField(default='', max_length=100),
        ),
    ]
