# Generated by Django 3.2.1 on 2021-07-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceScanModel', '0007_auto_20210728_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicescan',
            name='webvpn',
        ),
        migrations.AddField(
            model_name='servicescan',
            name='isVpn',
            field=models.CharField(default='', max_length=100),
        ),
    ]
