# Generated by Django 3.2.1 on 2021-07-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceScanModel', '0008_auto_20210728_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicescan',
            name='isVpn',
            field=models.BooleanField(default=False, max_length=100),
        ),
    ]
